name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make app
        make test

  build_debug:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make app DEBUG=1
        make test DEBUG=1

  run_test:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run-tests
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make run_tests

  run_test_debug:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run-tests
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make app DEBUG=1
        make run_tests DEBUG=1

  static_analyze:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: static-analyze
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make static_analyze

  memcheck:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run-memcheck
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make memcheck

  memcheck_debug:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run-memcheck
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make memcheck DEBUG=1