name: REGRESSION

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  regression:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: regression
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make regression

  regression_debug:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: regression
      env:
        CC: ${{ matrix.compiler }}
      run: |
        make config
        make regression DEBUG=1